### PR TITLE
Add ability to negate bool options using `--no-` prefix

### PR DESCRIPTION
**Pull request by theartoflogic**

### CODE REVIEW

**Comment by trentm** [comment]
Thanks for the PR!   I don't want to take this feature like this.... because the addition of `--no-` prefix handling definitely shouldn't be enabled all the time. The decision to support `--no-*` options should rest with the application using dashdash, not dashdash itself.

One way (if you are willing to work on it), that I think this could fit in would be: an optional `boolNegationPrefix` on boolean option specs. If that is defined, then option processing would
add handle that long option and use `false` as the value.  Having this be explicit would also
allow dashdash help output to mention the option.

```
var options = [
    {
        names: ['help', 'h'],
        type: 'bool',
        help: 'Print this help and exit.'
    },
    {
        names: ['butter'],
        type: 'bool',
        boolNegationPrefix: 'no-',
        help: 'Buttered?',
    },
];

// ...
```

and output:

```
$ node toast.js -h
usage: node toast.js [OPTIONS]
options:
    -h, --help      Print this help and exit.
    --[no-]butter   Buttered?
```

**Comment by theartoflogic** [comment]
It seems a little too redundant to have the parameter be at the option level only. There would be a lot of redundancy if the developer has to define the same `boolNegationPrefix` for every bool option (I assume that a developer who would use this would use it across the board most of the time, and wouldn't really have a different prefix for different options...at least, that's how I'm wanting to use it).

What do you think about having the `boolNegationPrefix` parameter be at the parser level and not the option level? That way you can set it when creating the parser instead of for each option definition. It could also be added at the option level to override the parser value if needed.

Example:

```js
var parser = dashdash.createParser({
    options: [
        {
            name: 'enable',
            type: 'bool',
            default: true
        }
    ],
    boolNegationPrefix: 'no-'
});

var options = parser.parse([
    '--no-enable'
]);

// { enable: false }

var options = parser.parse([ /* use default value */ ]);

// { enable: true }
```

Example with `off-` prefix:

```js
var parser = dashdash.createParser({
    options: [
        {
            name: 'enable',
            type: 'bool',
            default: true
        }
    ],
    boolNegationPrefix: 'off-'
});

var options = parser.parse([
    '--off-enable'
]);

// { enable: false }

var options = parser.parse([ /* use default value */ ]);

// { enable: true }
```

Example with option override:

```js
var parser = dashdash.createParser({
    options: [
        {
            name: 'enable',
            type: 'bool',
            default: true,
            boolNegationPrefix: 'off-'
        },
        {
            name: 'daemonize',
            type: 'bool',
            default: true
            // Use default negation prefix
        }
    ],
    boolNegationPrefix: 'no-'
});

var options = parser.parse([
    '--no-daemonize',
    '--off-enable'
]);

// { daemonize: false, enable: false }

var options = parser.parse([
    '--no-daemonize',
    '--no-enable'
]);

// throws invalid option exception due to wrong prefix
```

**Comment by trentm** [comment]
> What do you think about having the boolNegationPrefix parameter be at the parser level

Yes, having it at the parser top-level and at the option-level sounds good to me.

**Comment by theartoflogic** [comment]
Ok, I'll try and get an updated pull request in the next couple of days. Thanks for the feedback.

**Pull request closed without merging**
